name: plants_and_plans_mobile
description: "The mobile version of the plants and plans project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed: ^2.5.1
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^13.2.0
  gradient_borders: ^1.0.1
  plants:
    path: ../../packages/plants

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true