name: plants
description: plants
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  drift: ^2.20.1
  drift_flutter: ^0.1.0
  drift_local_storage_inspector: ^0.7.0
  flutter:
    sdk: flutter
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  path: ^1.9.0
  path_provider: ^2.1.4
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  build_runner: ^2.4.9
  drift_dev: ^2.20.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
